---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "http://catalogue"
---
apiVersion: v1
kind: Pod
metadata:
 name: cart
 labels:
  name: cart
  tire: app
spec:
 containers:
 - name: cart
   imagePullPolicy: Always
   image: sahiya/cart:k8
   envFrom:
   - configMapRef:
      name: cart-config
   resources:
    requests:
     cpu: "100m" ## 1cpu=1000mi cpu
     memory: "128Mi"
    limits:
     cpu: "100m"
     memory: "128Mi" 
   ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: cart-service
spec:
 selector: 
  name: cart
  tire: app
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080  
