---
apiVersion: v1
kind: Pod
metadata:
 name: mongodb
 labels:
  name: mongodb
  tire: db
spec:
 containers:
 - name: mongodb
   imagePullPolicy: Always
   image: sahiya/mongodb:k8
   ports:
    - containerPort: 27017
   resources:
       requests:
        cpu: "100m" ## 1cpu=1000mi cpu
        memory: "128Mi"
       limits:
        cpu: "100m"
        memory: "128Mi" 
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb-service
spec:
  selector: 
   name: mongodb
   tire: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 27017
