---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: app
spec:
  containers:
  - name: mongodb
    imagePullPolicy: Always
    image: sahiya/mongodb:k8.v1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tier: app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
