apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
  name: mysql
  tire: app
spec:
 containers:
 - name: mysql
   imagePullPolicy: Always
   image: sahiya/mysql:k8
   ports:
    - containerPort: 3306
   resources:
    requests:
     cpu: "100m" ## 1cpu=1000mi cpu
     memory: "128Mi"
    limits:
     cpu: "100m"
     memory: "128Mi" 
---
apiVersion: v1
kind: Service
metadata:
 name: mysql
spec:
 selector: 
  name: mysql
  tire: app
 ports:
 - protocol: TCP
   port: 80
   targetPort: 3306
