---
apiVersion: v1
kind: Pod
metadata:
 name: catalogue
 labels:
  name: catalogue
  tire: app
spec:
 containers:
 - name: catalogue
   imagePullPolicy: Always
   image: sahiya/catalogue:v1
   resources:
    requests:
     cpu: "100m" ## 1cpu=1000mi cpu
     memory: "128Mi"
    limits:
     cpu: "100m"
     memory: "128Mi" 
   ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: catalogue-service
spec:
 type: LoadBalancer
 selector: 
  name: catalogue
  tire: app
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080  
