---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: catalogue
    imagePullPolicy: Always
    image: sahiya/catalogue:k81
    resources:
      requests:
        cpu: "128m"
        memory: "152Mi"
      limits:
        cpu: "128m"
        memory: "152Mi"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
