---
apiVersion: v1
kind: Pod
metadata:
 name: web
 labels:
  name: web
  tire: frontend
spec:
 containers:
 - name: web
   image: sahiya/web:k8
   ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
 name: web-service
spec:
 type: LoadBalancer
 selector: 
  name: web
  tire: frontend
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80  
